name: Bug report
description: Create a report to help us improve DiscordLab
title: "[BUG] - "

labels:
  - bug

body:
  - type: checkboxes
    attributes: 
      label: Before continuing...
      description: Please confirm that you have completed the following steps
      options:
        - label: "I have searched the existing issues"
          required: true
        - label: "I have updated DiscordLab to the latest version"
          required: true
        - label: "I have checked the README"
          required: true

  - type: textarea
    attributes: 
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    attributes: 
      label: To Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: 1. Go to '...'
    validations:
      required: true
      
  - type: textarea
    attributes: 
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected to see...
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: What actually happened?
      description: A clear and concise description of what actually happened.
      placeholder: Instead I saw...
    validations:
      required: true
  
  - type: input
    attributes: 
      label: EXILED Version
      description: What version of EXILED are you using?
      placeholder: 8.14.0
    validations:
      required: true
  
  - type: textarea
    attributes: 
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: I was using the plugin...