name: "Build Project"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore NuGet packages
        run: nuget restore DiscordLab.sln
      - name: Build with msbuild
        run: msbuild DiscordLab.sln -t:rebuild /p:Configuration=Debug /p:LangVersion=latest
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DiscordLab
          path: |
            DiscordLab.Bot/bin/Debug/net48/DiscordLab.Bot.dll
            DiscordLab.BotStatus/bin/Debug/net48/DiscordLab.BotStatus.dll
            DiscordLab.ConnectionLogs/bin/Debug/net48/DiscordLab.ConnectionLogs.dll
            DiscordLab.DeathLogs/bin/Debug/net48/DiscordLab.DeathLogs.dll
            DiscordLab.StatusChannel/bin/Debug/net48/DiscordLab.StatusChannel.dll